config/routes.rb
Typio::Application.routes.draw do
  resources :notes

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root :to => "home#index"
end
#== Route Map
# Generated on 08 Oct 2013 23:57
#
#               new_user_session GET        /users/sign_in(.:format)                  devise/sessions#new
#                   user_session POST       /users/sign_in(.:format)                  devise/sessions#create
#           destroy_user_session DELETE     /users/sign_out(.:format)                 devise/sessions#destroy
#                  user_password POST       /users/password(.:format)                 devise/passwords#create
#              new_user_password GET        /users/password/new(.:format)             devise/passwords#new
#             edit_user_password GET        /users/password/edit(.:format)            devise/passwords#edit
#                                PATCH      /users/password(.:format)                 devise/passwords#update
#                                PUT        /users/password(.:format)                 devise/passwords#update
#       cancel_user_registration GET        /users/cancel(.:format)                   devise_invitable/registrations#cancel
#              user_registration POST       /users(.:format)                          devise_invitable/registrations#create
#          new_user_registration GET        /users/sign_up(.:format)                  devise_invitable/registrations#new
#         edit_user_registration GET        /users/edit(.:format)                     devise_invitable/registrations#edit
#                                PATCH      /users(.:format)                          devise_invitable/registrations#update
#                                PUT        /users(.:format)                          devise_invitable/registrations#update
#                                DELETE     /users(.:format)                          devise_invitable/registrations#destroy
#              user_confirmation POST       /users/confirmation(.:format)             devise/confirmations#create
#          new_user_confirmation GET        /users/confirmation/new(.:format)         devise/confirmations#new
#                                GET        /users/confirmation(.:format)             devise/confirmations#show
#         new_admin_user_session GET        /admin/login(.:format)                    active_admin/devise/sessions#new
#             admin_user_session POST       /admin/login(.:format)                    active_admin/devise/sessions#create
#     destroy_admin_user_session DELETE|GET /admin/logout(.:format)                   active_admin/devise/sessions#destroy
#            admin_user_password POST       /admin/password(.:format)                 active_admin/devise/passwords#create
#        new_admin_user_password GET        /admin/password/new(.:format)             active_admin/devise/passwords#new
#       edit_admin_user_password GET        /admin/password/edit(.:format)            active_admin/devise/passwords#edit
#                                PATCH      /admin/password(.:format)                 active_admin/devise/passwords#update
#                                PUT        /admin/password(.:format)                 active_admin/devise/passwords#update
#                     admin_root GET        /admin(.:format)                          admin/dashboard#index
# batch_action_admin_admin_users POST       /admin/admin_users/batch_action(.:format) admin/admin_users#batch_action
#              admin_admin_users GET        /admin/admin_users(.:format)              admin/admin_users#index
#                                POST       /admin/admin_users(.:format)              admin/admin_users#create
#           new_admin_admin_user GET        /admin/admin_users/new(.:format)          admin/admin_users#new
#          edit_admin_admin_user GET        /admin/admin_users/:id/edit(.:format)     admin/admin_users#edit
#               admin_admin_user GET        /admin/admin_users/:id(.:format)          admin/admin_users#show
#                                PATCH      /admin/admin_users/:id(.:format)          admin/admin_users#update
#                                PUT        /admin/admin_users/:id(.:format)          admin/admin_users#update
#                                DELETE     /admin/admin_users/:id(.:format)          admin/admin_users#destroy
#                admin_dashboard GET        /admin/dashboard(.:format)                admin/dashboard#index
#    batch_action_admin_comments POST       /admin/comments/batch_action(.:format)    admin/comments#batch_action
#                 admin_comments GET        /admin/comments(.:format)                 admin/comments#index
#                                POST       /admin/comments(.:format)                 admin/comments#create
#                  admin_comment GET        /admin/comments/:id(.:format)             admin/comments#show
#                           root GET        /                                         home#index

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/notes_controller.rb
class NotesController < InheritedResources::Base
  
  def index
    @notes = []
  end
  
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<div class="yin">
    <div class="overlay">
        <div class="wordcount modal">
            <h1>Target Word Count</h1>
            <div>
                <input type="number" name="quantity" value="0" min="0"></input>
            </div>
        </div>
        <div class="description modal">
            <h1> About ZenPen </h1>
            <p>  Zenpen is a minimalist writing zone by <a href="http://tholman.com">Tim Holman</a> (<a href="http://twitter.com/twholman">@twholman</a>), to get you into that zone, where you can focus on the writing - with none of the distractions. ZenPen is open source on <a href="http://github.com/tholman/zenpen">Github</a> (with many improvements on the way!). If you have any questions, hit me up via <a href="mailto:timothy.w.holman@gmail.com">email</a> - ooh, you can follow me on twitter for updates too: <a href="http://twitter.com/twholman">@twholman</a> </p>
        </div>
        <div class="saveoverlay modal">
            <h1>Select save format</h1>
            <p class='saveselection'>
                <span data-format='markdown'>Markdown</span>
                <span data-format='html'>HTML</span>
                <span data-format='plain'>Plain Text</span>
            </p>
            <button class='savebutton useicons'>&#xe006;</button>
            <div> Or select format and press ctrl+c (cmd+c on mac) to copy the text. </div>
            <textarea class='hiddentextbox'></textarea>
        </div>
    </div>
    <div class="text-options">
        <div class="options">
            <span class="no-overflow">
            <span class="lengthen ui-inputs">
            <button class="url useicons">&#xe005;</button>
            <input class="url-input" type="text" placeholder="Type or Paste URL here"/>
            <button class="bold">b</button>
            <button class="italic">i</button>
            <button class="quote">&rdquo;</button>
            </span>
            </span>
        </div>
    </div>
    <div class="ui">
        <div class="wrapper">
            <div class="top editing animated bounceInUp">
                <button class="fullscreen useicons" title="Toggle fullscreen">
                &#xe000;
                </button>
                <button class="color-flip useicons" title="Invert colors">
                &#xe001;
                </button>
                <button class="target useicons" title="Set target word count">
                &#xe00d;
                </button>
                <button class="save useicons" title="Save Text">
                &#xe00f;
                </button>
                <button class="tag useicons" title="Tag">
                &#xe008;
                </button>
            </div>
    	</div>
    </div>
    <div class="word-counter">
        <span class="progress"></span>
    </div>
    <section>
    	<header contenteditable="true" class="header">
    		Edge Cache Location Architecture
    	</header>
        <div data-toggle="pen" data-placeholder="" class='editable content'>
    		 
    		  <h2>Enjoy live editing (+markdown)</h2>

    		  <p><b><i>Click to edit, Select to apply effect, click items of toolbar to toggle effects.</i></b></p>
    		  <hr>
    		  <p>Horizontafsdfl-Rule can be insert by click「...」on the toolbar or just type「... 」/「--- 」/「*** 」at line start. Note that
    		    there's a SPACE at the end of a command.</p>
    		  <hr>
    		  <p>To link or unlink, please press the <i>ENTER</i> key after you filled the input field with your a link. A <a href="/sofish">link</a> can be unlink by apply an empty value to the input field.

    		  </p><p>
    		  </p><ul>
    		    <li>Ordered list and unordered list is supported.</li>
    		    <li>Use the toolbar or use markdown syntax like「<b>1. </b>」,「<b>- </b>」or「<b>* </b>」</li>
    		  </ul>
    		  <blockquote>You can quote text by type「<b>&gt;</b>」at line start.</blockquote>
    		  <p>What about add underline to text? "<u>Stay Hungry, Stay Foolish - <i>Steve Jobs</i></u>".</p>
    		  <pre>A code block is also support by type 「```」 at line start and press SPACE.</pre>
    		  <p>For more, please checkout: <a href="https://github.com/sofish/pen#readme" target="_blank">https://github.com/sofish/pen#readme</a>
    		  </p>
    		 
        </div>
    </section>
</div>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>